Fix link error with Rblas and undefined symbol
LinkError: imported unshared memory but shared required
Undefined symbol: _QQclX4E now replaced with undefined R_NaInt