Add r-base (#1287)
* Add R-base recipe

* Update recipe

* Update lfortran

* Add fPIC flag

* Update flags

* Add config patch

* Fix bad substitution

* Skip date-time conversions check

* Working config

* Replace lfortran

* Use existing stpcpy

* WIP

* WIP

* Almost building

* WIP

* Fix R executable

* Fix doc build

* Clean up

This works!

* Add comments

* Add rlang recipe

* Working recipe

* Fix r-base Makeconf vars

* Update build script

* Enable shared libs

* Add note about flags

* Copy wasm file

* Update dependencies

* Fix invalid assignment

* Working tests

* Working recipe

* Set default R home patch

* Increase stack size

* Add memory growth

* Clean up flags

* Add more linker flags

* Enable static

* Remove unsupported funs

* Update script

* Replace local flang

* Remove r-rlang

* Add modularized test

* Set identical versions for llvm and flang

* Clean patches

* Remove extra -lz

* Override some shared flags

* Update test

* Override -shared

* Fix link error with Rblas and undefined symbol

LinkError: imported unshared memory but shared required
Undefined symbol: _QQclX4E now replaced with undefined R_NaInt

* Remove more unsupported system calls

* Reset build number

* Rebuild

* Clean up